name: WalkingParticles
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.walkingparticles.Main

permissions:
  particle.angryvillager:
    description: ""
    default: false
  particle.bonemeal:
    description: ""
    default: false
  particle.bubble:
    description: ""
    default: false
  particle.critical:
    description: ""
    default: false
  particle.enchant:
    description: ""
    default: false
  particle.enchantmenttable:
    description: ""
    default: false
  particle.entityflame:
    description: ""
    default: false
  particle.explode:
    description: ""
    default: false
  particle.flame:
    description: ""
    default: false
  particle.happyvillager:
    description: ""
    default: false
  particle.heart:
    description: ""
    default: false
  particle.ink:
    description: ""
    default: false
  particle.lavadrip:
    description: ""
    default: false
  particle.lava:
    description: ""
    default: false
  particle.portal:
    description: ""
    default: false
  particle.rainsplash:
    description: ""
    default: false
  particle.redstone:
    description: ""
    default: false
  particle.smoke:
    description: ""
    default: false
  particle.spore:
    description: ""
    default: false
  particle.waterdrip:
    description: ""
    default: false
  particle.water:
    description: ""
    default: false